apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-gateway-api-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-gateway-api-controller
subjects:
  - kind: ServiceAccount
    name: ingress-gateway-api-controller
    namespace: ingress-gateway-api
